### ISSUE TITLE
JSON meta plugin doesn't work when depcache/building

### ISSUE THREAD

**Issue by happylinks** [systemjs/systemjs#1066]
I'm having some problems with the bundle or depcache command. Suddenly they don't recognize the json plugin anymore and look for .json.js.
I'm confident this used to work, but I'm not sure what I changed that broke it.

Config:
```
"packages": {
    "src": {
      "meta": {
        "*.jst": {
          "loader": "jst"
        },
        "*.json": {
          "loader": "json"
        }
      }
    }
  },
```

Import:
```
import environment from './environment.json';
```

Error:
```
jspm depcache src/index.js
     Injecting the traced dependency tree for src/index.js...

err  Error on fetch for src/environment.json at file:///Users/michiel/Projects/Project/src/environment.json.js
	Loading src/index.js
	Loading src/common/helpers/logPerformance.js
	Error: ENOENT: no such file or directory, open '/Users/michiel/Projects/Project/src/environment.json.js'
         at Error (native)
```

**Comment by happylinks** [comment]
The "packages" config seems to be ignored when I call the commands, it ignores jst and json.

**Comment by happylinks** [comment]
If I use the "meta" option I can set it up correctly for 1 file.
Like this:

```
packages: {
    "src": {
      "meta": {
        "*.jst": {
          "loader": "jst"
        },
        "*.json": {
          "loader": "json"
        }
      }
    }
  },

**  meta: {
    "src/environment.json": { "loader": "json" }
  },**
```

**Comment by guybedford** [comment]
Is this with or without the `defaultJSExtensions` option set?

**Comment by guybedford** [comment]
I assume it is set.

This may be due to a regression which was fixed in https://github.com/systemjs/systemjs/commit/86be5c4ac790be35ad065bef031a0f2ebc1e93ce pending release. If you're able to test out that patch let me know.

**Comment by happylinks** [comment]
Yeah, defaultJSExtensions is set to true in the systemjs config.
I tested your patch but unfortunately it didn't solve it, the reasing being that pkgName stays undefined.
I tried logging a bit and it never goes in this if-case because pkg is not set.
```
if (defaultExtension == undefined && pkg && pkg.meta)
```
I logged the packagename:
```
var pkgName = getPackage(this, decanonicalized);↵
       console.log('packagename', pkgName);↵
```
and got the following result:
```
packagename undefined

err  Error on fetch for src/environment.json.js at file:///Users/michiel/Projects/Golfy/GolfyAssistantWebapp3/src/environment.json.js
	Loading src/index.js
	Loading src/common/helpers/logPerformance.js
	Error: ENOENT: no such file or directory, open '/Users/michiel/Projects/Golfy/GolfyAssistantWebapp3/src/environment.json.js'
         at Error (native)

packagename undefined
```

Let me know if I can help you, or if there is another way to achieve this that is better.

**Comment by guybedford** [comment]
Are you including this package config along with the production bundle:

```javascript
packages: {
    "src": {
      "meta": {
        "*.jst": {
          "loader": "jst"
        },
        "*.json": {
          "loader": "json"
        }
      }
    }
  },
```

?

**Comment by happylinks** [comment]
I have one config.js in my folder which contains that packages-config and run this command:
```
jspm depcache src/index.js
```
My understanding was that it would automatically get that config.js. Do you mean something else with "the production bundle"?

**Comment by guybedford** [comment]
Thanks so much, this turned out to be a more fundamental bug than expected, which has likely resolved a number of path bugs now.

Fixed in https://github.com/systemjs/systemjs/commit/22240f80b7a749b03726a56e7c929cd62e4d1df8 and in https://github.com/systemjs/builder/commit/28010b922c899574b1f72bd23205707f38391ceb.

**Comment by happylinks** [comment]
Awesome! Thanks for the fix, I'll try it as soon as it is released :)

**Comment by happylinks** [comment]
Also, if I can help with JSPM/SystemJS or anything, let me know. I won't mind spending some free time on it.

**Comment by guybedford** [comment]
@happylinks help on the projects is very much welcome. SystemJS is pretty much complete at this point but help on any SystemJS builder and jspm issues you hit up against would be amazing.

**Comment by guybedford** [comment]
Generally it is all about focusing on workflow polishing, and ensuring that little bugs and features can be corrected to enable workflows as smoothly as possible.

**Comment by guybedford** [comment]
Released in 0.19.18.

**Comment by happylinks** [comment]
It worked! Building works again :)
Small details: SystemJS Builder isn't updated in NPM yet, and I think the dependency in JSPM repo should also be updated to the correct version.

**Comment by arcanis** [comment]
@guybedford I think this issue is still there: https://wisembly.github.io/DaMovieQuiz/ It fails to find the `systemjs-plugin-babel@0.0.17.json` file, despite it being inside the `deps.js` bundle. I think it's because it seems to be registered as `System.defined["https://wisembly.github.io/jspm_packages/npm/systemjs-plugin-babel@0.0.17.json.js"]` (notice the `.json.js`).
