### ISSUE TITLE
SystemJS wrapping in require on XHR load breaks sourcemap association

### ISSUE THREAD

**Issue by sparkbuzz** [systemjs/systemjs#1084]
I've been battling with Google Chrome for a while with not being able to set breakpoints in our JS files loaded via SystemJS. Typically, when setting a breakpoint in Chrome, the breakpoint jumps to some arbitrary line.

When SystemJS loads our JS files, it wraps the loaded source in a require block, thus disassociating our loaded JS from its corresponding sourcemap, causing the weird behaviour in the debugger.

```
(function(require, exports, module, __filename, __dirname, global, GLOBAL) {
    // Our code loaded with SystemJS via XHR goes here...
}).apply(__cjsWrapper.exports, __cjsWrapper.args);
```

Is there a way we can rather have this wrapping / modification done on the server side, in our Gulp pipeline, so that we can maintain the integrity of our sourcemaps?

**Comment by guybedford** [comment]
Always nice to get issue reports from CT :)

So we actually don't add a newline to that wrapper (`(function(require, ...) {<code here>`), which means it is only the first line of the source map that has its references altered (it's a bit of a cheat but it works).

The issue here is actually that evaluation via `new Function(source)` causes a line offset to be added to the source map. I'm wondering if that is a browser bug or if we should aim to move back to eval without `new Function`.

**Comment by sparkbuzz** [comment]
Thanks @guybedford Can we possibly have the files be changed server side, via our gulp pipeline, to maintain the sourcemap integrity?

**Comment by guybedford** [comment]
@sparkbuzz sure the workaround would be exactly this modification to the source map - https://github.com/systemjs/systemjs/blob/master/lib/global-eval.js#L51. We should aim to fix it properly though here too.

**Comment by sparkbuzz** [comment]
What about using this? https://github.com/systemjs/builder Will that fix our sorrows? Perhaps we could also get back source files for Safari and Firefox, if we load the generated stuff through script tags. Currently only Chrome understands and interprets the JS source through XHR, as source, if you know what I mean.

**Comment by guybedford** [comment]
Unfortunately the builder doesn't support chaining with source maps from source map comments. Also there is a source maps offset bug in the builder as well being tracked in https://github.com/systemjs/builder/issues/489.

**Comment by sparkbuzz** [comment]
Awesome, I guess that was worth the try, thanks for that. Back to your original workaround then:

> sure the workaround would be exactly this modification to the source map - https://github.com/systemjs/systemjs/blob/master/lib/global-eval.js#L51. We should aim to fix it properly though here too.

I'm not sure I understand 100% what you meant. Should something change with or around our sourcemap? Just on a side note, our sourcemaps are inline at present.

**Comment by guybedford** [comment]
It's a direct modification to the source map itself to handle the line offset.

I've implemented https://github.com/systemjs/systemjs/commit/30b0f8bf85b3f653379b6c6c4f61582f6b4ac12a which should resolve this now.

**Comment by sparkbuzz** [comment]
Thanks Guy. I npm installed from that commit and rebuilt my project. Chrome console is open with "Disable cache" turned on. Made double sure I'm running from your latest commit. The issue still happens. I set a breakpoint in one of my .js files and it jumped from line 43 to 49.

**Comment by guybedford** [comment]
It requires a `npm install && make` to run the `dist` version of the code on master. It should definitely work now. The other thing to do is to check the underlying source map itself by dragging the source into this great tool - http://sokra.github.io/source-map-visualization/.

**Comment by sparkbuzz** [comment]
Oh, this source map tool is awesome, I was looking for something like that. Thanks for all your help Guy! Will let you know if this works, might only be Monday morning, as it's getting a bit late.

**Comment by sparkbuzz** [comment]
Hi @guybedford. CT bugging again. I've taken the following steps this morning:

  - Entirely uninstall systemjs from my project.
  - Re-install master with the following command: `npm install systemjs/systemjs`
  - Ran `npm install && make`
  - Rebuild my assets by doing `gulp clean` and then rebuilding.
  - Refreshed project in Chrome, and confirmed that I don't have an old copy of system.src.js cached.
  - Also did a spot check diff with your latest commit, to confirm I actually have the latest code.

Breakpoints assignment in Chrome still jumps around sporadically, here's what I can find, using Google Chrome 48.0.2564.103 (64-bit):

When setting a BP on the last line of a block, the BP jumps to the parent block definition. For example if I have:

```
class Test {
    constructor() {
        line_1();
        console.log('blah');
    }
}
```

...setting a BP on `console.log...`, the BP jumps to `constructor()`

Quite often, the BP simply jumps to the next line, even for single line statements.

Most of the time, setting a BP on a line starting a block, for example an if statement, the BP jumps to the line following the next statement, after the closing brace of that respective block. For example:

```
if (today == 'monday') {
    // omitted
}
console.log('hello');
```

...setting a BP on the if statemtent, BP jumps to console.log.

I have compared our sourcemaps on the sourcemap visualization tool you linked to, and all the blocks appear to be linking up as expected. I've even turned off stuff in our Gulp pipeline like uglify, so only have BabelJS transpilation going on using the ES2015 preset.

I'm just wondering if this is not Google Chrome that's being wonky?

**Comment by sparkbuzz** [comment]
Hi @guybedford I've created a small project here: https://github.com/sparkbuzz/systemjs_issue_1084 which shows how I'm producing the issue. Simply checkout, run `npm install`, also do your `npm install && make` bit for systemjs in node_modules, and then `run gulp`. The HelloWorld.js file contains comments with where the breakpoints are jumping to.

**Comment by guybedford** [comment]
@sparkbuzz I think this is actually just a browser bug or due to limitations in source maps themselves. The fact that some lines work and some don't shows that they are lining up correctly though. Source maps are known to be limited, see also http://fitzgeraldnick.com/weblog/62/.

**Comment by guybedford** [comment]
As well, inspecting the source map in the visualizer shows that the alignments aren't quite right either. Checking the lines that are shown to jump often match multiple mappings, or cross boundaries slightly. This is likely the underlying cause.

**Comment by sparkbuzz** [comment]
Thanks for looking into this @guybedford. I had a bit of a brainwave. According to https://kangax.github.io/compat-table/es6/ Chrome Canary v50 already has about 91% support for ES6 out of the box, no transpilation necessary.

So to debug in Canary, I simply skip the transpilation step in Gulp, turn off sourcemaps for JavaScript and debug using the original source files. Seems to work really well so far. 

Off course this won't help with browsers with lacking support, and for anyone else out there reading this,  make sure you test your transpiled code thoroughly.
