### ISSUE TITLE
Error with systemjs builder and fetch: this.defined is undefined

### ISSUE THREAD

**Issue by nkassis** [systemjs/systemjs#1379]
I'm getting a weird error with trying to to use the systemjs builder. This was working on friday. 

Used jspm dl-loader --latest to get version 0.19.34

Error: 

> 
> Message:
>     Error on fetch for npm:aurelia-framework@1.0.0-beta.1.2.5.js at file:///<redacted>/jspm_packages/npm/aurelia-framework@1.0.0-beta.1.2.5.js
>         Cannot read property 'file:///<Redacted>jspm_packages/npm/aurelia-framework
> @1.0.0-beta.1.2.5.js' of undefined
> Details:
>     originalErr: TypeError: Cannot read property 'file:///<Redacted>jspm_packages/n
> pm/aurelia-framework@1.0.0-beta.1.2.5.js' of undefined
> Stack:
> Error on fetch for npm:aurelia-framework@1.0.0-beta.1.2.5.js at file:///<Redacted>j
> spm_packages/npm/aurelia-framework@1.0.0-beta.1.2.5.js
>         TypeError: Cannot read property 'file:///<Redacted>jspm_packages/npm/aureli
> a-framework@1.0.0-beta.1.2.5.js' of undefined
>     at <Redacted>node_modules\systemjs-builder\node_modules\systemjs\dist\system.sr
> c.js:3377:23
>     at <Redacted>node_modules\systemjs-builder\node_modules\systemjs\dist\system.sr
> c.js:3696:18
>     at <Redacted>node_modules\systemjs-builder\node_modules\systemjs\dist\system.sr
> c.js:4088:18
>     at <Redacted>node_modules\systemjs-builder\node_modules\systemjs\dist\system.sr
> c.js:4551:22
>     at <Redacted>node_modules\systemjs-builder\node_modules\systemjs\dist\system.sr
> c.js:4820:20
>     at cachedFetch (<Redacted>node_modules\systemjs-builder\lib\builder.js:178:40)
>     at SystemJSNodeLoader.<anonymous> (<Redacted>node_modules\aurelia-bundler\dist\
> bundler.js:75:14)
>     at SystemJSNodeLoader.loader.fetch (<Redacted>node_modules\systemjs-builder\lib
> \builder.js:196:44)
>     at <Redacted>node_modules\systemjs-builder\lib\trace.js:434:12
>     at tryCatcher (<Redacted>node_modules\systemjs-builder\node_modules\bluebird\js
> \release\util.js:16:23)
>     at Promise._settlePromiseFromHandler (<Redacted>node_modules\systemjs-builder\n
> ode_modules\bluebird\js\release\promise.js:504:31)
>     at Promise._settlePromise (<Redacted>node_modules\systemjs-builder\node_modules
> \bluebird\js\release\promise.js:561:18)
>     at Promise._settlePromise0 (<Redacted>node_modules\systemjs-builder\node_module
> s\bluebird\js\release\promise.js:606:10)
>     at Promise._settlePromises (<Redacted>node_modules\systemjs-builder\node_module
> s\bluebird\js\release\promise.js:685:18)
>     at Async._drainQueue (<Redacted>node_modules\systemjs-builder\node_modules\blue
> bird\js\release\async.js:138:16)
>     at Async._drainQueues (<Redacted>node_modules\systemjs-builder\node_modules\blu
> ebird\js\release\async.js:148:10)
>     at Immediate.Async.drainQueues (<Redacted>node_modules\systemjs-builder\node_mo
> dules\bluebird\js\release\async.js:17:14)
>     at runCallback (timers.js:570:20)
>     at tryOnImmediate (timers.js:550:5)
>     at processImmediate [as _immediateCallback] (timers.js:529:5)
> 

Seems to be failling at on the 3 line here: 

```
hook('fetch', function(fetch) {
    return function(load) {
      if (this.defined[load.name]) {
        load.metadata.format = 'defined';
        return '';
      }

      load.metadata.deps = load.metadata.deps || [];
      
      return fetch.call(this, load);
    };
});
```
I can see the files on disc in the right location : \jspm_packages\npm\aurelia-framework@1.0.0-beta.1.2.5

Any idea what's going on? 

Thanks

**Comment by guybedford** [comment]
This should be fixed in the latest SystemJS builder patch release. jspm releases are coming through now.

**Comment by wegorich** [comment]
The `0.19.35` version still have the issue.

For now @nkassis you may follow solution from there
https://github.com/aurelia/bundler/issues/136

It seems the hook 'fetch' loose the context at 3rd line
```
1. hook('fetch', function(fetch) {
2.    return function(load) {
3.      if (this.defined[load.name]) {
```

https://github.com/wegorich/systemjs/commit/90e4eff29f0f8b7493b55546dccda0eadd5d1d51

**Comment by guybedford** [comment]
Make sure to update systemjs builder.

**Comment by nkassis** [comment]
Can confirm this now resolved with latest version.
