### ISSUE TITLE
SystemJS 0.21.1 breaks with various `Unable to load transpiler to transpile` errors

### ISSUE THREAD

**Issue by timvandermeij** [systemjs/systemjs#1809]
This worked fine with SystemJS 0.21.0, but no longer works with SystemJS 0.21.1.

Steps to reproduce:

    $ git clone https://github.com/mozilla/pdf.js.git
    $ cd pdf.js
    $ npm install
    $ gulp server

Open `http://localhost:8888/examples/helloworld/index.html` in the browser and notice the hello world PDF being rendered. Now run:

    $ npm install systemjs@0.21.1
    $ gulp server

Open `http://localhost:8888/examples/helloworld/index.html` in the browser and notice the hello world PDF not being rendered anymore. In the console the following error is shown:

```
Error: this is undefined
  Evaluating http://localhost:8888/node_modules/systemjs-plugin-babel/systemjs-babel-browser.js
  Evaluating http://localhost:8888/node_modules/systemjs-plugin-babel/plugin-babel.js
  Evaluating http://localhost:8888/external/systemjs/plugin-babel-cached.js
  Loading plugin-babel-cached
  Unable to load transpiler to transpile http://localhost:8888/src/display/api.js
  Instantiating http://localhost:8888/src/display/api.js
  Loading pdfjs/display/api
```

Is there something that we should do on our side about this or is this a regression in version 0.21.1?

**Comment by guybedford** [comment]
Thanks, yes this was a regression due to indirect eval being lost in the build (`eval` over `0,eval`).

I've released a 0.21.2 with the fix.

**Comment by timvandermeij** [comment]
I can still reproduce this with version 0.21.2, so it looks like it's not fixed yet.

**Comment by arantius** [comment]
> I can still reproduce this with version 0.21.2, so it looks like it's not fixed (completely) yet. Could you reopen this?

I see this error in 0.21.1 and 0.21.2.  Reverting to 0.21.0 makes it go away.

**Comment by guybedford** [comment]
This should be ok in 0.21.3, but please let me know if you're still seeing this at all.
