### ISSUE TITLE
exported module fails to load scoped variables

### ISSUE THREAD

**Issue by flasaracina** [systemjs/systemjs#1905]
Hello, I have this code

```js
import { Broker as EventBroker, Publisher, Subscriber, Event } from "message-broker";
import { EVENTS } from "./events";

class KernelStatusEvent extends Event{
    constructor( status ){
        super(EVENTS.STATUS);
        this.status = !!status? "busy" : "idle";
    }
}

export function Busy( scope ){
    let isBusy, Busy;
    Busy = ( value ) =>{
        if( undefined === value ){
            return !!isBusy;
        }
        isBusy = !!value;
        console.log("KernelStatusEvent", KernelStatusEvent);
        return scope.publisher.fire(EVENTS.STATUS, new KernelStatusEvent(!!value), scope);
    }

    Busy.subscribe = ( handler, once ) =>{
        let sub = {};

        sub[EVENTS.STATUS] = { method: handler, once: !!once };
        scope.Bus.add(new Subscriber(sub));
    }
    return Busy;
}
```

when I run it Systemjs tells me that KernelStatusEvent is not defined, but as you can clearly see from the code above it is defined in the same file of the exported function (aka the scope MUST be the same)

It is worth noticing that this same code worked flawlessly in a Systemjs 0.20 environment.

How can I fix this? Thank you for your help

**Comment by paulkenney** [comment]
Are you transpiling this file to the 'system' format before trying to load it? If not, that's your first problem since SystemJS 2+ only supports 'system', 'amd', and 'wasm' formats. Use babel or rollup to do the conversion, then you can load it into SystemJS.

If you are already doing all that, more information is probably needed.

**Comment by flasaracina** [comment]
@paulkenney Thank you for the fast reply!

I am using SystemJS 2+ with the following "transform"s:

- extras/transform
- systemjs-transform-babel

as per systemjs-transform-babel plugin usage guide found on the repo.

I tried to convert `KernelStatusEvent` class into a function (good ol' JS way) and it gets imported without problems. So it fails whenever it tries to import a class into the scope.

Thanks again

**Comment by flasaracina** [comment]
I have found a workaround to the problem but it is just a "hack".

instead of:

```javascript
export function Busy( scope ){
    //code...
}
```
if I write:

```javascript
export const Busy = function( scope ){
    //code...
}
```
It can "see" the class in the function scope correctly.

I don't know why this happens and I think it is worth investigating more on the cause of the issue since it is not obvious that if you export a function like I did at the beginning it will messes with the JS scope.

What do you think? @paulkenney 

Thank you for your time

**Comment by guybedford** [comment]
@flasaracina which version of systemjs-transform-babel are you using here?

**Comment by flasaracina** [comment]
@guybedford I am using `systemjs-transform-babel` 0.1.0 via 
`npm install systemjs-transform-babel`

so I assume that 0.1.0 is the latest one. Am I correct?

Thanks again. Much appreciated

**Comment by guybedford** [comment]
Ahh, I believe this is the bug I fixed in https://github.com/babel/babel/pull/8820 then. I've shipped a version of the babel transform with the update (0.1.1), let me know if that fixes it for you.

**Comment by flasaracina** [comment]
@guybedford Thanks! It was it! It works now!

**Comment by flasaracina** [comment]
@guybedford 
I made a comment in which I said that everything worked fine, but it didn't. I deleted that comment now.
I rushed a bit and called it a day too soon, sorry!

Unfortunately the error still appears

**Comment by guybedford** [comment]
@flasaracina it would help if you can share the exact error here, because I suspect this may just be the way "ES modules work". Did you try running the same code example with just native ES modules?

**Comment by flasaracina** [comment]
@guybedford with systemjs 0.2+ I don't have this issue at all and my code runs flawlessly. I am trying to migrate it to systemjs2+ for maintenability.

anyway, this is the error I get:

Uncaught (in promise) ReferenceError: KernelStatusEvent is not defined
    at Busy (busy.js? [sm]:13)
    at new Kernel (kernel.js? [sm]:64)
    at new Application (application.js? [sm]:54)
    at Object.execute (main.js? [sm]:10)
    at doExec (system.js:433)
    at postOrderExec (system.js:429)
    at system.js:380

It originates from the code I've written at the top.

Thanks

**Comment by guybedford** [comment]
It would help if you can isolate the exact issue - eg is it due to a ‘this’
reference in the function? Etc

**Comment by flasaracina** [comment]
Let's simplify the thing a bit. in an empty folder let's do this:

```bash 
   npm init -y
   npm install esm
```
then let's create an `index.js` like this:

```javascript
import { Busy } from './busy';

const whatever = Busy();
whatever(true);
```

and the the `busy.js` file like this:

```javascript
class KernelStatusEvent{
    constructor( status ){
        this.status = !!status? "busy" : "idle";
    }
}

export function Busy(){
    let isBusy, Busy;
    Busy = ( value ) =>{
        if( undefined === value ){
            return !!isBusy;
        }
        isBusy = !!value;
        console.log("KernelStatusEvent", KernelStatusEvent);
    }

    return Busy;
}
```
if I run

`node -r esm index.js`

it will output the content of the class without errors

**Comment by flasaracina** [comment]
@guybedford 
I don't think is a `this` problem because It fails to interpret `KernelStatusEventArgs` as a class.

If it was a `this` problem we should've had an error like

`Uncaught TypeError: Cannot read property 'whatever' of undefined`

or a thing like that

**Comment by guybedford** [comment]
Thanks @flasaracina for the test case - it turns out this is actually a pretty important bug in the System Babel transform. The fix is at https://github.com/babel/babel/pull/9639, which will take a few weeks to land and release now.

In the mean time, your arrow function workaround sounds like a sensible approach.

**Comment by flasaracina** [comment]
@guybedford  thank you for the quick reply and fix! I'll keep an eye on the Babel transform repo for the update. Thanks again

**Comment by guybedford** [comment]
@flasaracina to let you know,  the Babel update finally landed and I've released systemjs-transform-babel with the fix.

**Comment by flasaracina** [comment]
Thank you for letting me to know. I'll check it as soon as possible
