### ISSUE TITLE
How to catch SystemJS Errors?

### ISSUE THREAD

**Issue by leonheess** [systemjs/systemjs#2294]
- SystemJS Version: _6.8.3_
- Which library are you using?
  - [x] system.js
  - [ ] s.js
  - [ ] system-node.cjs
- Which extras are you using?
 _None_
- Are you using any [custom hooks](/docs/hooks.md)?
 _No_
### Question

I'm getting the following error, which is fine in and of itself but I want to catch it if it occurs.
```
Uncaught (in promise) Error: Unable to resolve bare specifier 'redacted' from http://localhost:3000/ (SystemJS Error#8 https://git.io/JvFET#8)
    at throwUnresolved (system.js:698)
    at SystemJS.systemJSPrototype.resolve (system.js:694)
    at system.js:227
```

My code:

```
window.System.import('redacted')
  .then(x => do(x))
  .catch(() => doSomethingElse()),
```
I expect the catch to prevent any errors from showing up in the console and executing `doSomethingElse()` but neither is happening.

**Comment by guybedford** [comment]
@leonheess make sure to try with the latest version of SystemJS - 6.8.3. I believe this should be working correctly.

**Comment by leonheess** [comment]
@guybedford Unfortunately this problem persists with 6.8.3 :/

**Comment by guybedford** [comment]
@leonheess just tested this out and it seems to be working ok for me - 

![Uploading image.png…]()

are you sure you refreshed the cache when upgrading? Perhaps it's something else?

**Comment by leonheess** [comment]
Weird, I can't reproduce it anymore. I guess it was cache after all. Sorry for bothering you and thanks!

**Comment by guybedford** [comment]
No problem, thanks for reporting anyway.

**Comment by rDr4g0n** [comment]
I was able to repro this (in v6.8.3) by using a URL instead of bare specifier:

    System.import("https://localhost:8089/totally-invalid.js").catch(e => console.log("aw shucks"))

![image](https://user-images.githubusercontent.com/1927558/105753169-df453380-5f0d-11eb-9c64-d97ca84e7e30.png)

It looks like the failure occurs when the [script tag is inserted into the document head](https://github.com/systemjs/systemjs/blob/abccaf09a54b125150a8be663218d0ba08a5ce90/src/features/script-load.js#L86). This also causes the uncaught error to only occur once, presumably because it doesn't try to reinsert the script tag.

**Comment by guybedford** [comment]
@rDr4g0n I can't replicate the error not firing the second time in this case either - can you send an exact example?

**Comment by rDr4g0n** [comment]
Here is an example of the console output. I request the same bad file 3 times. The first one throws an uncaught error, the next 2 do not throw an uncaught error. Then, i request a different bad file 3 times. It throws the first time, and not the subsequent times.

![image](https://user-images.githubusercontent.com/1927558/106029822-17c24a00-6093-11eb-90ee-d346aa93e03c.png)

Also, only 2 network requests are made:

![image](https://user-images.githubusercontent.com/1927558/106029982-49d3ac00-6093-11eb-9e81-ac6fb0dd333a.png)

**Comment by guybedford** [comment]
@rDr4g0n this is because errors are cached. We aim to follow what browsers do though, if they change we can change.

**Comment by rDr4g0n** [comment]
@guybedford the caching behavior is not a problem; I just pointed it out as a potentially useful detail. Per the initial ticket: Is there any way I can catch the error?

**Comment by guybedford** [comment]
@rDr4g0n the six lines of "aw shucks" are you catching the error.

**Comment by rDr4g0n** [comment]
@guybedford Sorry, I meant the idea of catching the error such that it doesnt make it all the way to the console as an uncaught error. The `GET ... net::ERR_CONNECTION_REFUSED` is what I would like to catch and avoid showing in the console.

**Comment by guybedford** [comment]
@rDr4g0n I don't actually think there's a way to do that, it's not an error being logged (it's not a JS error object, but a browser fetch error I think). If there was a good suggestion for hiding these I'm all for it though.

**Comment by guybedford** [comment]
So I don't think there's a way to hide the console error for `document.body.appendChild(Object.assign(document.createElement('script'), { src: './notfound.js' }))`, but please prove me wrong.

**Comment by rDr4g0n** [comment]
@guybedford It seems you are correct. You can catch script errors, but cannot prevent them :(

Thanks for the help.
