### ISSUE TITLE
system-polyfills (v0.17.1) auto-loading fails in asynchronous environment on IE and Safari

### ISSUE THREAD

**Issue by pgbross** [systemjs/systemjs#495]
I have an offline capable web app that has an app cached page and a minimal script that loads my main application from local storage on iPads, Android devices, and Windows tablets. On Safari and IE, they require the URLPolyfill and normally this would be auto-detected and loaded by systemjs and "injected" using document.write as a script on the original server.

In my environment, as the html and scripts are loaded from local storage document.load() has completed, so the document.write() will replace the entire DOM html which obviously breaks. I therefore tried manually registering the system-polyfills.js script before loading the system.js script. The registration of URLPolyfill() works (and in a debugger it appears on the global window object as I am in a browser), but the detection of support for URL as a function does not check to see if URLPolyfill() is available, so still tries a document.write() even though it is already present. If I comment out  the document.write() and just call bootstrap(), it loads my application successfully, so the registration of URLPolyfill() is good, but the auto-injection is not detecting its presence.

Is there another mechanism by which I should be registering system-polyfills manually, or is should the detection code in systemjs/lib/wrapper-end.js be using logic more like that in es6-module-loader/src/wrapper-start.js where it doesn't load the polyfill if URLPolyfill is present?

thanks,
--philip

**Comment by guybedford** [comment]
Thanks for posting, what you are doing is exactly correct. I've added a fix for the polyfill detection in https://github.com/systemjs/systemjs/commit/f1b0ac39c1ba364b6318a3040dcffc4320a1bea7.

**Comment by pgbross** [comment]
Thanks for confirming I am using the polyfill as expected. Looking at your proposed fix in 0.17.2-dev, I think you have a typo - you have URLPollyfill whereas it should be URLPolyfill (one el in poly).

**Comment by guybedford** [comment]
Thanks, I've fixed that up.

**Comment by guybedford** [comment]
Released in SystemJS 0.18.

**Comment by gearsdigital** [comment]
This seems to be still broken in Safari 8.0.6 (10600.6.3)...

**Comment by guybedford** [comment]
Thanks for the follow up, I've fixed this in https://github.com/systemjs/systemjs/commit/acfa4305eda0b41cd43c8079bb2ca626844b0e5a and https://github.com/ModuleLoader/es6-module-loader/commit/6c6a6a2bff7d937484c531ad2b647be022a4e0d5.

**Comment by gearsdigital** [comment]
You're very welcome. Thanks for your effort...
