### ISSUE TITLE
`.js` appended to folder name.

### ISSUE THREAD

**Issue by Zoltu** [systemjs/systemjs#540]
I have no idea how to debug this so I am starting by posting this issue here.  Please let me know if the problem is elsewhere.

1. `mkdir test`
1. `cd test`
1. `npm init` (all defaults)
1. `npm install jspm@beta`
1. `node_modules/.bin/jspm install aurelia-bootstrapper` (all defaults)
1. Create index.html (see below)
1. `npm install http-server`
1. `node_modules/.bin/http-server`
1. Navigate to `localhost:8080`
1. Notice that the page fails to load and console reports errors fetching files that don't exist.

index.html
```html
<!doctype html>
<html>
<body aurelia-app>
    <script src="jspm_packages/system.js"></script>
    <script src="config.js"></script>
    <script>
        System.import('aurelia-bootstrapper');
    </script>
</body>
</html>
```
After loading several files, this error occurs:
```
http://localhost:3000/jspm_packages/github/aurelia/templating-resources@0.12.1.js/compose.js 404 (Not Found)
```
It is followed by several more similar errors.  The problem is that `.js` is appended to the folder name after the version number.

Note: If you look at what files are fetched, you can see that `compose.js` was successfully loaded earlier on.

Is this a problem with Aurelia?  JSPM?  SystemJS?

**Comment by guybedford** [comment]
It's definitely working fine for me. Did you run `jspm dl-loader`? Are you running on Windows?

**Comment by Zoltu** [comment]
I don't know what `dl-loader` is, do I need to run that for things to work?  I am on Windows.

I was just able to reproduce it again.  I have updated my original issue post above with more specific repro steps.  Please let me know if those same steps do not repro for you.  I am using node `v0.12.2`, npm `2.7.4` and Windows `8.1`.

Note: If I do `npm install jspm` instead (no beta) then everything works, implying this is a problem with JSPM or SystemJS (possibly a breaking change with 0.17).

**Comment by guybedford** [comment]
`jspm dl-loader` will update the existing loader files in an existing project.

It's definitely working fine for me in windows, so I think you just need to run that.

**Comment by Zoltu** [comment]
Executing `jspm dl-loader` did not resolve the issue.  I would have been surprised if it did as this is a brand new project, right down to creating a new folder and executing commands entirely within that folder (no copying from outside, other than `npm` and `jspm` commands).

I just reproduced the problem in a brand new Nitrous.io Node.js container by following the exact steps listed above.  Perhaps clearing your JSPM cache will cause the problem to reproduce?

**Comment by guybedford** [comment]
Try running on SystemJS master via `jspm dl-loader --edge`. I think this may have been fixed already.

**Comment by Zoltu** [comment]
The problem persists after running `jspm dl-loader --edge` both in the Nitrous.io container and locally on my Windows machine.

**Comment by guybedford** [comment]
Did you try clearing the cache - `jspm cc`?

**Comment by guybedford** [comment]
I've tried it on master and beta on Windows and it's absolutely fine. I'd suggest checking carefully you're definitely doing it out-of-the-box. If you can share a test case after install that might help here.

**Comment by Zoltu** [comment]
The problem persists after running `jspm cc` (Nitrous.io and Windows).  Though, do I need to do anything after running `jspm cc` before I can expect to see a change?

To reiterate, the above commands were run on a brand new box in the nitrous.io scenario (a box that has never seen JSPM/Aurelia before).  Even if this was a caching issue I believe there is still a bug here since out of the box things are not working.

**Comment by guybedford** [comment]
You'll have to meet me halfway - I've run fresh installs 4 times on my custom VM. There is nothing more I can do without more help from you to replicate.

**Comment by Zoltu** [comment]
https://github.com/Zoltu/systemjs-bug-repro

Let me know what else I can do to help you repro this.  I have no idea why it isn't reproing for you.  It sounds like both of us are starting from scratch and getting different results, which suggests that we are doing something different.

I am explicitly installing all NPM packages locally, perhaps you are using a global install of JSPM and that is the difference?  I try to avoid global installs of NPM packages, but I can try to repro with a global install if you believe that will alter the results?

**Comment by Zoltu** [comment]
Would you like me to create a repro that doesn't have node_modules and jspm_packages ignored?

**Comment by guybedford** [comment]
Right, the difference is the existence of the `aurelia-app` in the body tag - ie the bootstrapping process. Thanks for this - it's good to know that Aurelia isn't working against the beta - I've posted https://github.com/aurelia/bootstrapper/issues/10.

**Comment by Zoltu** [comment]
Thanks!

**Comment by damianof** [comment]
This might not be completely fixed. I have update to latest aurelia, 0.13.2, and getting a bunch of these 404 errors in the browser console (for templating-resources and templating-router):

/jspm_packages/github/aurelia/templating-resources@0.13.0/compose.html 404 (Not Found)
...
/jspm_packages/github/aurelia/templating-router@0.14.0/router-view.html
...

**Comment by damianof** [comment]
I have <body aurelia-app="main"> and in my main.js file i am loading aurelia-validation and datatables.
When i commented out the aurelia-validation line it works
export function configure(aurelia) {
aurelia.use
.standardConfiguration()
.developmentLogging()
.plugin('aurelia-validation')
.plugin('datatables');
aurelia
    .start()
    .then(a => a.setRoot()); 
}
I had 0.2.4 of aurelia-validation. So i upgraded to latest which is0.2.6, but still no luck
So not sure if aurelia-validation is still not up to date with this issue here , or maybe this one https://github.com/aurelia/bootstrapper/issues/10

**Comment by damianof** [comment]
Disregard my previous comment. I fixed this by modifying the config.js file for aurelia-validation:
"github:aurelia/validation@0.2.6": {
      "aurelia-binding": "github:aurelia/binding@0.8.1",
      "aurelia-dependency-injection": "github:aurelia/dependency-injection@0.9.0",
      "aurelia-templating": "github:aurelia/templating@0.13.2"
    }
