### ISSUE TITLE
__moduleName is always the same (with systemjs@0.18.4)

### ISSUE THREAD

**Issue by andreasgrimm** [systemjs/systemjs#619]
I just tried running one of my apps with jspm@beta (0.16.0-beta.3 at the time of install). As the majority of it's modules depend on the implicit variable `__moduleName` I found out that when using systemjs@0.18.4 the value of `__moduleName` is the same in all module bodies (maybe the name of the first module body that accessed the variable, I don't know exactly yet).

btw: I noticed that in contrast to e.g. systemjs@0.16.11 the format of the module name obviously changed in systemjs@0.18.4. But as I couldn't keep up with all the changes happening recently, I guess I just missed that one and the reason why it changed.

Switching back to jspm@0.15.7 that uses systemjs@0.16.11 solved the issue and it worked again. Each module accessing `__moduleName` now get's an individual value again.

**Comment by guybedford** [comment]
Thanks, I believe this was fixed in https://github.com/ModuleLoader/es6-module-loader/commit/23cdde56817c9d27f552cfc419406960df34591f and a release will follow soon. Perhaps run SystemJS master in the mean time.

**Comment by andreasgrimm** [comment]
no problem. I guess I'll just wait for jspm@0.16 being released and then I'll notice right away might this issue still be the case :)

**Comment by andreasgrimm** [comment]
as babel doesn't support emitting `__moduleName` (anymore), is there an (official) alternative to access kind of a unique identifier from within a module?

**Comment by guybedford** [comment]
`__moduleName` is entirely a SystemJS construct and is supported in builds in SystemJS. There will be a metadata system in modules, what is currently proposed is something like `import.name` inside of a module. The standardization of such a syntax is still happening though, and as soon as it is set we will implement it in System.register as part of the module format.

**Comment by guybedford** [comment]
Released in 0.18.5.
