### ISSUE TITLE
Angular config module fetched but not executed 

### ISSUE THREAD

**Issue by defyjoy** [systemjs/systemjs#792]
I have a angular app which has two files . app.js  and route.config.js . The module is loaded through import statement . But what happens is the module is loaded but not executed for some reason . I can see in the network tab of chrome that all the files are getting loaded but when I put breakpoint on the route config which is supposed to render the template . Its not getting executed . And also added more to the problem , its kind of weird and inconsistent . Sometimes it runs all fine when I hit the url . the route config loads and renders the template . But sometimes the routeconfig doesn't execute at all . Added to that . There are no console errors at all which might cause the issue .

here are the two files .

First app.js :

```javascript
'use strict';

import "angular";
import "angular-ui-router";
import {default as routeconfig} from "app/common/config/routes.config";
import 'bootstrap';
import 'bootstrap/css/bootstrap.css!';
import 'bootstrap/css/bootstrap-theme.css!';

angular.module('app',['ui.router'])

angular.element(document).ready(function() {
    angular.bootstrap(document,['app']);
});

angular.module('app').config(routeconfig.factory);
```

Second file : route.config.js 

```javascript
import "angular";
import "angular-ui-router";

class RouteConfig {
    
    constructor($stateProvider, $urlRouterProvider){
        this.stateProvider = $stateProvider;
        this.urlRouterProvider = $urlRouterProvider;

        $stateProvider
            .state("index", {
                url: "/",
                templateUrl: "/app/common/templates/home.html",
            })
            .state('order',{
                url:'/order',
                templateUrl:"/app/modules/order/templates/order.html",
                controller:"order.controller as orderCtrl",
                resolve:{
                    load:()=>{
                        System.import('app/modules/order/order.module');
                        System.import('app/modules/order/order.controller');
                    }
                }
            });
        
        $urlRouterProvider.otherwise("/");
    };

    static factory($stateProvider, $urlRouterProvider){
        RouteConfig.instance = new RouteConfig($stateProvider,$urlRouterProvider);   
        return RouteConfig.instance;
    };
}

RouteConfig.factory.$inject = ['$stateProvider', '$urlRouterProvider'];

export default RouteConfig;
```

I also tried adding the below code to config.js . Bit it didn't help .
```
 "meta": {
        "*.js": {
            "format": "register"
        }
    }
 ````

**Comment by defyjoy** [comment]
Ok This issue was for 0.16.11

**Comment by guybedford** [comment]
Thanks for the update, are you saying this issue is resolved for you in 0.18?

**Comment by defyjoy** [comment]
On 0.18 the issue is something else . 
![image](https://cloud.githubusercontent.com/assets/1047068/9954628/352240d4-5e08-11e5-9b8e-26880fed11f7.png)

this is the issue for 0.18

**Comment by defyjoy** [comment]
I just removed the 
```
 "meta": {
        "*.js": {
            "format": "register"
        }
    }
``` 

section . The above error was gone . But back to sqaure one . It doesn't execute the constructor . The OP issue is back

**Comment by guybedford** [comment]
Just to check the obvious - you are bootstrapping Angular manually here right?

**Comment by guybedford** [comment]
(https://docs.angularjs.org/guide/bootstrap#manual-initialization to be specific)

**Comment by defyjoy** [comment]
yes its manual bootstraping for angular

**Comment by guybedford** [comment]
I still think this sounds like this is more of an Angular issue than a module loading issue though.

For example, if you put a console.log in the app or routing file at the top, you are seeing the code execute, so it's entirely about information flow within Angular.

Could it be something like the ordering here:

```javascript
angular.module('app',['ui.router'])

angular.element(document).ready(function() {
    angular.bootstrap(document,['app']);
});

angular.module('app').config(routeconfig.factory);
```

Say the ready function called back before the last line about ran, you might bootstrap before having the route configured or something like that? Does moving that last line up help?

**Comment by defyjoy** [comment]
Yes I moved it just after the `angular.module('app',['ui.router'])` . It now hits the breakpoint inside `routes.config.js` . Can you please explain more of it . I was under impression that first angular bootstrapping should happen and then the routes should be configured via angular.config . But now it seems like the execution order is first the routes are configured and then the angular is bootstrapping once the document is ready ? 

```
angular.module('app',['ui.router'])
angular.module('app').config(routeconfig.factory);


angular.element(document).ready(function() {
    angular.bootstrap(document,['app']);
});


```

**Comment by guybedford** [comment]
I'm not an Angular expert, so not sure what to suggest in terms of architecture here.

**Comment by guybedford** [comment]
Just let me know if I can help you further here at all.
